#!/bin/bash
#SBATCH -J wDPD
#SBATCH -n 1 -N 1
#SBATCH -t 24:00:00
#SBATCH -p short
#SBATCH --constraint=ib
##SBATCH --mem=128Gb
#SBATCH -o %A.out
#SBATCH -e %A.err

module purge
module load python/3.8.1
# add path-to-hoomd-basic: 
source /work/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 
# ex: /work/props/your-name/software/hoomd4.2.1-basic/hoomd-venv/bin/activate
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# note: you cannot initialize a system with mpi
python3 sim-waterDPD.py
