#!/bin/bash

#SBATCH -J plot
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-plot.out
#SBATCH -e %A-plot.err

module load python/3.8.1
# add path-to-hoomd-mod: 
source # ex: /work/props/your-name/software/hoomd4.2.1-basic/hoomd-venv/bin/activate

# run the plot file
python plot-kT.py
python plot-shearstress.py
